### ISSUE TITLE
Missing image for code 521

### ISSUE THREAD

**Issue by Dav-Git** [httpcats/http.cat#100]
Missing cat for status code 521 Web Server Down commonly used by the cloud flare service

**Comment by Ryuno-Ki** [comment]
Do you have a suggested cat image to show?
As far as I know, PRs with added images have a chance to get accepted.

**Comment by Dav-Git** [comment]
Sadly I'm more of a programmer than I am a Photographer. I only noticed a in my opinion relatively prominent missing code and would leave it to someone else to create a corresponding picture with their artistic skills.

**Comment by TheAwesome98-Real** [comment]
Maybe a cat lying upside-down might do the trick?

**Comment by fafrd** [comment]
Suggesting my cat here for 2 cloudflare status codes. (these are my photos and I grant permission to use them for any purpose)

### HTTP 521: web server is down
![httpcat serverdown](https://user-images.githubusercontent.com/5905628/124820177-fc047f00-df21-11eb-965d-3172a18dabb6.jpeg)

### HTTP 523: origin is unreachable
![httpcat unreachable](https://user-images.githubusercontent.com/5905628/124820172-fad35200-df21-11eb-8dda-4e95d29e2d6d.jpeg)
