### ISSUE TITLE
Can I buy you a pizza

### ISSUE THREAD

**Issue by sean-hill** [httpcats/http.cat#130]
This is literally the best website ever. Please let me send you something for making me happy. 🍕

**Comment by rogeriopvl** [comment]
Hi @sean-hill thank you so much for the praise 🙏  I'm really glad that you enjoy http.cat.

If you want to contribute, please checkout the [Patreon page](https://www.patreon.com/httpcat).

**Comment by sean-hill** [comment]
@rogeriopvl sounds good!
