### ISSUE TITLE
Missing status: 308 Permanent Redirect

### ISSUE THREAD

**Issue by katrinleinweber** [httpcats/http.cat#15]
> [...] target resource has been assigned a new permanent URI and any future references to this resource ought to use one of the enclosed URIs.

https://tools.ietf.org/html/rfc7538

Or just reuse https://http.cat/301 because it's almost the same?

**Comment by Jo-Seungjun** [comment]
in my guess, she is not on the bitch by her willing

also, HTTP 308 has to force

so how about [this](https://i.ytimg.com/vi/55iBoIePvao/maxresdefault.jpg) ?

**Comment by katrinleinweber** [comment]
If you mean beach, then yes ;-)

**Comment by rogeriopvl** [comment]
If anyone wants to come up with a PR for this I'll be glad to merge it :)

**Comment by manuelprinz** [comment]
> HTTP 308 has to force

I am not sure if understand you correctly but there is no force with this code. 308 is "permanent". That only means that it is cached by default. The difference between 308 and 301 is that 308 does not change the request method. (301 indicates a change of method; usually from POST to GET.) You could interpret 301/308 "cat-wise" as "this cat intentionally moved to the proposed location and intents to stay". But I am not sure what the "same request method" would translate to. This is a question for more creative minds. :wink:
