### ISSUE TITLE
Is the cat in 499 okay

### ISSUE THREAD

**Issue by gastrodon** [httpcats/http.cat#152]
Is he okay? [http.cat/499](https://http.cat/499)

**Comment by daviddev16** [comment]
Probably yes, lmao xD

**Comment by sanjai0py** [comment]
[yes!](https://www.reddit.com/r/pics/comments/czlgl/a_few_years_ago_my_cat_lulu_got_stuck_in_my/?utm_source=share&utm_medium=web2x&context=3)
