### ISSUE TITLE
Unable to switch back to english version from català

### ISSUE THREAD

**Issue by jd-develop** [httpcats/http.cat#155]
The link at the bottom of the page is still “Versió Català”.

**Comment by rogeriopvl** [comment]
Hi @jd-develop 

Thanks for the report. This will be addressed in the next version of http cats. I'll leave this open until then.

**Comment by jd-develop** [comment]
The link just disappeared from the main page in English. I guess there’s no more Català version and therefore this issue is no longer useful?

**Comment by rogeriopvl** [comment]
@jd-develop The Catalan version is temporarily disabled because I'm currently implementing translations in a different way.

**Comment by elena20ruiz** [comment]
Hello @rogeriopvl ! is the new translation implementation ready? I would love to have the català version again, and if so, help with the catalan PR.

**Comment by rogeriopvl** [comment]
Hi @elena20ruiz , unfortunately I haven't been able to get around it. I would definitely appreciate your PR. Let me know if you need any context :)

**Comment by arham-sayyed** [comment]
Can you please provide more context, i cannot find how to change the language. in order to test this bug, or is it fixed already?

**Comment by just-max** [comment]
Seems like this is fixed now, the link at the bottom of the page works (but directly navigating to the URL: https://http.cat/ca/ does not)

**Comment by rogeriopvl** [comment]
This is now fixed. @just-max thanks for spotting the direct navigation issue, it should also be fixed now 👍
