### ISSUE TITLE
Status code for 404 is unavailable?

### ISSUE THREAD

**Issue by argontheory** [httpcats/http.cat#158]
For some reason, this is what is being sent to the client on https://http.cat/404:
![image](https://github.com/httpcats/http.cat/assets/70502391/1ec5949f-1882-46aa-a822-de82ce7261a7)
Not the 404 I expected.. 😕

**Comment by rogeriopvl** [comment]
Hey @argontheory 

Thanks for reporting this. It's fixed now.

**Comment by argontheory** [comment]
Do I have to wait for the changes to be deployed to the website?

**Comment by rogeriopvl** [comment]
If it's still showing, you probably just need to clear your browser's cache.

[!404](https://http.cat/404)
