### ISSUE TITLE
Description for 425 seems incorrect

### ISSUE THREAD

**Issue by joselialcosta** [httpcats/http.cat#19]
Hello maintainer of this cute repository!

Me and @richardcsantana noticed that 425 http code, according with RFC is about "Too early", but in the site it is represented by "Unordered collection"

[RFC](https://tools.ietf.org/html/rfc8470#section-5.2) 📚 
[Page](https://http.cat/425) 🐱 

Count with us if you need some support to fix it. We found this [image](https://icatcare.org/sites/default/files/kcfinder/images/images/kitten-handrearing.jpg) that we judge as appropriate.

**Comment by rogeriopvl** [comment]
Hi @joselialcosta thanks for reporting this. It's actually weird, but apparently that status code was a draft that became obsolete at some point.

cc @girliemac

**Comment by masukomi** [comment]
According to the wayback machine this is the image @joselialcosta suggested. I second their suggestion. :) 

![425_too_early](https://user-images.githubusercontent.com/2829/90173944-33e75e80-dd73-11ea-808e-0c6fd49816c4.jpg)

**Comment by girliemac** [comment]
Aw, I wasn't aware of the change. Thank you! Another "too early" ideas I can think of are: 
https://www.pxfuel.com/en/free-photo-ojrwg 
https://pxhere.com/en/photo/1045245
as "too early (in the morning)" 😪
There are royalty-free pics

**Comment by rogeriopvl** [comment]
Closed by #80 

Thanks for the suggestions everyone!
