### ISSUE TITLE
Missing status: 407 Proxy Authentication Required

### ISSUE THREAD

**Issue by Terones** [httpcats/http.cat#20]
407 Proxy Authentication Required
Similar to [401 Unauthorized](http://http.cat/401), but it indicates that the client needs to authenticate itself in order to use a proxy.

**Comment by Terones** [comment]
I'm not sure what the rules are on the images, but I kinda like this one:
http://www.catsvscancer.org/wp-content/uploads/2015/11/cats-wait-in-line.png

**Comment by rogeriopvl** [comment]
Hi @Terones thanks for the suggestion. I'm not actively adding images myself due to lack of time for this project.

All new statuses are being added by contributors. So if you feel like it, please submit a pull request with your suggestion, I'll be glad to review it and add it to the project.
