### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by nivex** [httpcats/http.cat#67]
Please enable IPv6 support on http.cat.

I see it is being hosted on DigitalOcean. Instructions to enable: https://www.digitalocean.com/docs/networking/ipv6/how-to/enable/

Thanks!

**Comment by telmich** [comment]
I'd really look forward for IPv6 support, too

**Comment by Jamim** [comment]
Hi there,
[http.cat](https://http.cat) is already [available](https://ready.chair6.net/?url=https%3A%2F%2Fhttp.cat) via IPv6, so I believe this issue might be resolved.
