### ISSUE TITLE
Isnt it supposed to give us the actual status code?

### ISSUE THREAD

**Issue by rodrigograca31** [httpcats/http.cat#70]
I thought making a request to `https://http.cat/404` would return a page with an actual 404 status code... 🤔

Isn't that the idea for this site? or is it just the images?

**Comment by Jo-Seungjun** [comment]
in my thought, this project is functioning as an image provider

someone who needs an image for their project could get an image source from this project

also, it is pretty hard to create such codes as long as this project is a serverless project

**Comment by tusharsadhwani** [comment]
Would be cooler and just as functional imo if it returned the same status code 🐱

**Comment by fafrd** [comment]
I think you're misunderstanding the concept of an API. If I want to build something that uses httpcat as a backend image provider, I can't have it returning random HTTP error codes, my client would interpret this as a real, valid error.

**Comment by TheEssem** [comment]
Would it at least be possible to provide a separate endpoint that does return the same status code? It would be very useful for testing application behavior.

**Comment by rogeriopvl** [comment]
@TheEssem I can think about it since there seems to be some demand. It would have to be done as an optional behavior.

**Comment by fafrd** [comment]
This website will return the HTTP code for testing: https://statuscodes.org
for example, https://statuscodes.org/418
