### ISSUE TITLE
Missing status : 102 - Processing

### ISSUE THREAD

**Issue by woutfeys** [httpcats/http.cat#77]
We have a missing status (102) I think we could do a cat with a loading icon on his head?
Update : creating the image

**Comment by woutfeys** [comment]
![image](https://user-images.githubusercontent.com/28490560/97109775-6ef00180-16d5-11eb-86f0-e76f0a453d6e.png)
I'm refering to this meme

**Comment by rogeriopvl** [comment]
Closed by #78
