### ISSUE TITLE
Missing image for 203 status code 

### ISSUE THREAD

**Issue by astercraker** [httpcats/http.cat#87]
Hey! 👋

The image for code (HTTP) 203 Non-Authoritative Information is missing

**Comment by Jo-Seungjun** [comment]
not every status code is applied

**Comment by astercraker** [comment]
Like this image [https://www.google.com/url?sa=i&url=https%3A%2F%2Fhu.pinterest.com%2Fpin%2F234116880608429151%2F&psig=AOvVaw2OJ9a1P6wdF2-JK04qPTPu&ust=1610494635778000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCMivpseGle4CFQAAAAAdAAAAABAK](image)
